name: "Build"

on:
  push:
    branches:
      - '**'
  schedule:
    # Customise: Cron interval
    - cron: "0 12 * * *"
  workflow_dispatch:
    inputs:
      regenerate:
        description: Enter csv of recipe slugs to specifically regenerate
        required: false
        type: string
      skip:
        description: Enter csv of recipe slugs to specifically skip
        required: false
        type: string
      verbose:
        description: Run recipe in verbose mode
        required: false
        type: boolean

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.ref_name == github.event.repository.default_branch
    # Customise: Total job run time limit
    timeout-minutes: 45
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install npm dependencies
        run: npm install -g sass terser html-minifier-terser

      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 1

      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install python requirements
        run: pip install -r requirements.txt

      - name: Install calibre dependencies
        run: sudo apt-get update -y && sudo apt-get install --no-install-recommends -y libegl1 libopengl0

      - name: Install calibre
        run: |
          mkdir -p ~/calibre-bin
          wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sh /dev/stdin install_dir=~/calibre-bin isolated=y
          export PATH=$PATH:$HOME/calibre-bin/calibre
          calibre --version
          echo "$HOME/calibre-bin/calibre" >> $GITHUB_PATH

      - name: Cache
        id: cache
        uses: actions/cache@v3
        with:
          path: cache
          key: cache

      - name: Generate .mobi
        env:
          CALIBRE_CONFIG_DIRECTORY: ${{ github.workspace }}/calibre_config/
          regenerate: ${{ github.event.inputs.regenerate }}
          skip: ${{ github.event.inputs.skip }}
          verbose: ${{ github.event.inputs.verbose }}
        run: |
          export CI_PAGES_URL="https://${GITHUB_REPOSITORY_OWNER}.github.io${GITHUB_REPOSITORY:${#GITHUB_REPOSITORY_OWNER}}/"
          sh _build.sh
          if [[ -f 'job_summary.md' ]]; then cat 'job_summary.md' >> $GITHUB_STEP_SUMMARY; fi
          echo -e "\n<"'!'"-- Commit ${GITHUB_SHA:0:7} -->" >> public/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v1
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./public
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
